### ISSUE TITLE
NPE in NotifyHandler

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#117]
It seems that the failing chaos runs causes some problems in the notify handler

```java
java.lang.NullPointerException at io.zeebe.clustertestbench.handler.NotifyEngineersHandler.composeMessage(NotifyEngineersHandler.java:65) at io.zeebe.clustertestbench.handler.NotifyEngineersHandler.handle(NotifyEngineersHandler.java:24) at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Zelldon** [comment]
Problem is that the NotifyHandler expects:

```
{
	"testReport": {
		"testResult": "FAILED",
		"startTime": 1603611756279,
		"endTime": 1603611815878,
		"timeOfFirstFailure": 1603611767472,
		"failureCount": 1,
		"failureMessages": ["Iteration 0 exceeded maximum time of PT10S; elapsedTime: PT10.044S; metaData:{workflowInstanceKey=13510798882111559}"],
		"metaData": {
			"testParams": {
				"steps": 3,
				"iterations": 10,
				"maxTimeForIteration": "PT10S",
				"maxTimeForCompleteTest": "PT2M"
			}
		},
		"duration": 59599
	}
}


```

But we send the failureCount and failureMessages on root level.
