### ISSUE TITLE
Improve resilience when DNS record is not available

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#201]
We often have incidents in Operate because the DNS record could not be resolved. This happens very early in the process.

This should be detected and handled with a retry. 

Example stack trace for reference:

```
io.zeebe.client.api.command.ClientStatusException: Unable to resolve host 0f1ffb04-6758-4636-95a8-a58fc8931bb9.zeebe.ultrawombat.com at 
io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93) at 
io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50) at 
io.zeebe.clustertestbench.handler.WarmUpClusterHandler.handle(WarmUpClusterHandler.java:42) at 
io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) at 
io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) at 
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at 
java.base/java.util.concurrent.FutureTask.run(Unknown Source) at 
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at 
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at 
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source) 

Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host 0f1ffb04-6758-4636-95a8-a58fc8931bb9.zeebe.ultrawombat.com at 
java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source) at 
java.base/java.util.concurrent.CompletableFuture.get(Unknown Source) at 
io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48) ... 9 more 

Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host 0f1ffb04-6758-4636-95a8-a58fc8931bb9.zeebe.ultrawombat.com at io.grpc.Status.asRuntimeException(Status.java:533) at 
io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) at 
io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463) at 
io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427) at 
io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460) at 
io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616) at 
io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69) at 
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802) at 
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781) at 
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at 
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ... 3 more 

Caused by: java.lang.RuntimeException: java.net.UnknownHostException: 0f1ffb04-6758-4636-95a8-a58fc8931bb9.zeebe.ultrawombat.com at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223) at 
io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282) at 
io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318) ... 3 more 

Caused by: java.net.UnknownHostException: 0f1ffb04-6758-4636-95a8-a58fc8931bb9.zeebe.ultrawombat.com at 
java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) at 
java.base/java.net.InetAddress.getAllByName0(Unknown Source) at java.base/java.net.InetAddress.getAllByName(Unknown Source) at java.base/java.net.InetAddress.getAllByName(Unknown Source) at 
io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631) at 
io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219) ... 5 more
```

**Comment by npepinpe** [comment]
It may have been fixed by the DNS pre-provisioning that was deployed last Friday - please verify if this is still an issue.

**Comment by pihme** [comment]
Still an issue. Happened again today

**Comment by npepinpe** [comment]
Check with @ultraschuppi about this - he said it should work now, but even if it doesn't, we may need to wait for the cluster to be healthy first (maybe a different way of checking the health of the cluster?).

**Comment by pihme** [comment]
We already check for cluster health as reported by Console.

**Comment by pihme** [comment]
has not occurred again this quarter
