### ISSUE TITLE
Creation of generation fails with Internal server error

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-cluster-testbench#945]
After fixing https://github.com/camunda/zeebe/issues/14780 we experience during testing the e2e tests several internal server error.

Due to the wrong response mappings (interface of the Rest API) we can't see what the error message contains.

[This is the error we see:](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22testbench-1-x-prod%22%0Alabels.k8s-pod%2Fapp%3D%22testbench%22;cursorTimestamp=2023-11-24T11:02:23.372826663Z;startTime=2023-11-24T10:43:57.555Z;endTime=2023-11-24T12:43:57.555817Z?project=zeebe-io)

```
jakarta.ws.rs.client.ResponseProcessingException: java.io.IOException: Internal Server Error returned from URI: https://console.cloud.ultrawombat.com/external/generations/ee489414-071a-4194-a1ae-ead4183a2ae2, requestBody:{"name":"temp_W8gjazwI7R","zeebeVersion":"gcr.io/zeebe-io/zeebe:8.2.19-SNAPSHOT-stable-8.2-9d058e55","operateVersion":null}, responseBody: Cannot read properties of undefined (reading 'map')
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:671) ~[testbench.jar:3.0.5-SNAPSHOT]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:428) ~[testbench.jar:3.0.5-SNAPSHOT]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134) ~[testbench.jar:3.0.5-SNAPSHOT]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103) ~[testbench.jar:3.0.5-SNAPSHOT]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61) ~[testbench.jar:3.0.5-SNAPSHOT]
	at jdk.proxy2.$Proxy43.cloneGeneration(Unknown Source) ~[?:?]
	at io.zeebe.clustertestbench.handler.CreateGenerationInCamundaCloudHandler.cloneGeneration(CreateGenerationInCamundaCloudHandler.java:46) ~[testbench.jar:3.0.5-SNAPSHOT]
	at io.zeebe.clustertestbench.handler.CreateGenerationInCamundaCloudHandler.handle(CreateGenerationInCamundaCloudHandler.java:31) ~[testbench.jar:3.0.5-SNAPSHOT]
	at io.zeebe.clustertestbench.handler.JobHandlerWithEnrichedLogger.handle(JobHandlerWithEnrichedLogger.java:29) ~[testbench.jar:3.0.5-SNAPSHOT]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactoryImpl.executeJob(JobRunnableFactoryImpl.java:45) ~[testbench.jar:3.0.5-SNAPSHOT]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactoryImpl.lambda$create$0(JobRunnableFactoryImpl.java:40) ~[testbench.jar:3.0.5-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: Internal Server Error returned from URI: https://console.cloud.ultrawombat.com/external/generations/ee489414-071a-4194-a1ae-ead4183a2ae2, requestBody:{"name":"temp_W8gjazwI7R","zeebeVersion":"gcr.io/zeebe-io/zeebe:8.2.19-SNAPSHOT-stable-8.2-9d058e55","operateVersion":null}, responseBody: Cannot read properties of undefined (reading 'map')
	at io.zeebe.clustertestbench.cloud.filter.FailedResponseFilter.filter(FailedResponseFilter.java:38) ~[testbench.jar:3.0.5-SNAPSHOT]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:667) ~[testbench.jar:3.0.5-SNAPSHOT]
	... 16 more

```

![testbench](https://github.com/zeebe-io/zeebe-cluster-testbench/assets/2758593/cce5d82a-c426-4af7-b770-f217a9bf6ee0)

**Comment by Zelldon** [comment]
We need to improve our mapping here https://github.com/zeebe-io/zeebe-cluster-testbench/blob/main/external-console-api-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/ExternalConsoleAPIClient.java#L26 

So we can also see failed responses and map them correctly to better understand what is going on.

Console team doesn't see any errors on there side (I asked them yesterday.)

**Comment by Zelldon** [comment]
Related endpoint code at console https://github.com/camunda-cloud/camunda-cloud-management-apps/blob/40646e93c243e3af837c1e3304a43aa7517ba0a3/apps/console-backend/src/controller/external-api/external.generation.controller.ts#L90

**Comment by megglos** [comment]
ZDP-Triage:
- @Zelldon will this be handed over to the next medic? let's sync on the urgency, will put into backlog as upcoming for now
- also added it to the ZPA project

**Comment by Zelldon** [comment]
Looks like this was because of the newly created generations 8.2.0, 8.3.0 etc were not marked as upgradable from so we were not able to find them based on the code https://github.com/camunda-cloud/camunda-cloud-management-apps/blob/40646e93c243e3af837c1e3304a43aa7517ba0a3/apps/console-backend/src/controller/external-api/external.generation.controller.ts#L116C42-L116C42

**Comment by Zelldon** [comment]
https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/1731
